In [1]:
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()
en = ['The quick brown fox jumps over a lazy dog']
vect.fit(en)
vect.vocabulary_, len(vect.vocabulary_)

({'the': 7,
  'quick': 6,
  'brown': 0,
  'fox': 2,
  'jumps': 3,
  'over': 5,
  'lazy': 4,
  'dog': 1},
 8)

<font color=#FE2D00 face="黑体">Warning:</font> `feature_extraction.text` module cannot fit the Chinese!Usually we use `jieba` module

In [2]:
import jieba
cn=jieba.cut('那只敏捷的棕色狐狸跳过了一只懒惰的狗')
cn = [' '.join(cn)]
cn

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\ADAMSM~1\AppData\Local\Temp\jieba.cache
Loading model cost 0.659 seconds.
Prefix dict has been built successfully.


['那 只 敏捷 的 棕色 狐狸 跳过 了 一只 懒惰 的 狗']

In [3]:
vect.fit(cn)
len(vect.vocabulary_), vect.vocabulary_

(6, {'敏捷': 2, '棕色': 3, '狐狸': 4, '跳过': 5, '一只': 0, '懒惰': 1})

## 词袋模型将文本数据转为数组

In [4]:
bag_of_words = vect.transform(cn)
repr(bag_of_words), bag_of_words.toarray()

("<1x6 sparse matrix of type '<class 'numpy.int64'>'\n\twith 6 stored elements in Compressed Sparse Row format>",
 array([[1, 1, 1, 1, 1, 1]], dtype=int64))

## 使用`n-Gram`改善词袋模型

In [5]:
joke = jieba.cut('道士看见和尚亲吻了尼姑的嘴唇')
joke = [' '.join(joke)]
vect.fit(joke)
joke_feature = vect.transform(joke)
joke_feature.toarray()

array([[1, 1, 1, 1, 1, 1]], dtype=int64)

In [6]:
joke2 = jieba.cut('尼姑看见和尚亲吻了道士的嘴唇')
joke2 = [' '.join(joke2)]
vect.fit(joke2)
joke_feature2 = vect.transform(joke2)
joke_feature2.toarray()

array([[1, 1, 1, 1, 1, 1]], dtype=int64)

In [7]:
vect=CountVectorizer(ngram_range=(2,2))
cv = vect.fit(joke)
joke_feature=cv.transform(joke)
cv.get_feature_names(), joke_feature.toarray()

(['亲吻 尼姑', '和尚 亲吻', '尼姑 嘴唇', '看见 和尚', '道士 看见'],
 array([[1, 1, 1, 1, 1]], dtype=int64))

In [8]:
joke2_feature = vect.transform(joke2)
joke2_feature.toarray()

array([[0, 1, 0, 1, 0]], dtype=int64)

## tf-idf 模型对文本数据处理

In [13]:
from sklearn.datasets import load_files
train_set = load_files('Imdblite')
x_train, y_train = train_set.data, train_set.target
len(x_train)   # ???

0